### ISSUE TITLE
about dataset?

### ISSUE THREAD

**Issue by litingting1111** [utcsilab/diffusion-channels#1]
when i run main.py in MATLAB, it is not work.

**Comment by mariusarvinte** [comment]
Hi,

I am assuming you meant ```main.m```, from the ```matlab``` folder. Can you please provide more details about which line causes what error?

On my side, it all works using a clean Matlab ```R2021b``` install, with the ```Communications``` (https://www.mathworks.com/products/communications.html) and ```5G``` (https://www.mathworks.com/products/5g.html) Toolboxes - these are both required. The detailed steps are:

1. Make sure you download the latest version on the main branch.
2. Open Matlab and change the path to  ```your/local/path/score-based-channels/matlab```
3. Run ```main.m```

**Comment by litingting1111** [comment]
thanks, my Matlab version is R2018a, maybe i will try in the latest Matlab.

**Comment by mariusarvinte** [comment]
Indeed, switching to a newer version may do it. For a very quick test, if you can run the functions ```comm.SphereDecoder``` and ```nrCDLChannel``` in the console (just like that, no arguments) and not get a "Missing Toolbox Error", then you should be able to actually run the code.

I will add it to my list to include a link to a file with pre-generated channels, closing this issue for now, please feel free to re-open if there's anything else

**Comment by litingting1111** [comment]
Thanks for your replay. When I run MATLAB 2021b on my local windows computer, 70% of the dataset is completed in three days, is this normal? Maybe some datasets can be provided for training? It is so slow.

**Comment by mariusarvinte** [comment]
Indeed, it can be slow, but it also depends on your CPU capabilities; I would advise you to run this code on a workstation-grade platform, otherwise it's hard to interpret the value you posted. As a reference, on our server with dual Intel Xeon 6230 generating the training dataset takes approximately 12 hours.

I will look into sharing the datasets if possible, there are some size constraints in place.

**Comment by litingting1111** [comment]
Thank you very much for your reply.

**Comment by mariusarvinte** [comment]
Hi, following up on this, I have created a Dropbox link which contains pre-generated CDL-D channels (train, validation and test): https://www.dropbox.com/sh/rcfyde3ccaf3jqd/AABWo7-2DUAhv4EdtWwD-J9Ga?dl=0 (also reflected in ```readme.md```). These are only for wavelength 0.5 $\lambda$, I have updated the training and hyper-parameter code accordingly to only train and test on this wavelength.

For now this is the most we can offer as a public download, in the future we will create persistent links for more data. Feel free to reopen this issue if there are bugs encountered with the data.
