### ISSUE TITLE
About Lasso

### ISSUE THREAD

**Issue by zyy341** [utcsilab/diffusion-channels#2]
Hi,
I'm interested in the Lasso part, but I didn't find the code for the Lasso part.  Can you tell me where the code corresponding to the LASSO part is? 
Thank you！

**Comment by mariusarvinte** [comment]
Hi, thanks for your question.

To run Lasso, you can simply run `test_l1Fourier_lifted.py` with `--lifting 1`. That will use sparsity in the Fourier (beamspace) domain as a prior. You can check this on lines 144-152 in that file for the exact implementation.

Let me know if there's more questions.

**Comment by zyy341** [comment]
> 

I am very thankful that you reply me quickly.
