### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by userofwireless** [utcsilab/diffusion-channels#7]
I am encountering the following error. Please advise. I tried it for Python3.12 as well as 3.8.

$ pip install -r requirements.txt .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by mariusarvinte** [comment]
The exact command is `pip install -r requirements.txt` - without the `.` at the end. This works for me, feel free to re-open if there are remaining issues.
